/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlktx;

import java.text.SimpleDateFormat;
import qlktx.DAL.HoaDonDienNuoc_DAL;
import qlktx.DAL.Phong_DAL;
import qlktx.DAL.ThongTinHoaDon_DAL;
import qlktx.DTO.HoaDonDienNuoc_DTO;
import qlktx.DTO.Phong_DTO;
import qlktx.DTO.ThongTinHoaDon_DTO;

/**
 *
 * @author ASUS
 */
public class ctpForm extends javax.swing.JFrame {

    /**
     * Creates new form ctpForm
     */
    private String MaTT;
    
    private int month;
    private int year;
    private Phong_DTO phong = new Phong_DTO();
    private HoaDonDienNuoc_DAL tthd = new HoaDonDienNuoc_DAL();
    private HoaDonDienNuoc_DTO hd = new HoaDonDienNuoc_DTO();
    private Phong_DAL phongDAL = new Phong_DAL();
    
    public ctpForm(Phong_DTO phong) {
        initComponents();
        this.phong = phong;
        lblNgayTT.setVisible(false);
        txtNgayTT.setVisible(false);
        loadData();
        
    }
    
    public void loadData(){
        lblTenPhong.setText("Phòng " + phong.getMaP());
        month = monthChooser.getMonth() + 1;
        year = yearChooser.getYear();
        hd = tthd.timTheoPhongToa(phong.getMaT(),phong.getMaP(), month, year);
        txtNoiDungHD.setText(hd.getChiTiet());
        txtTongHD.setText(String.valueOf(hd.getTongTien()));
        txtLoaiPhong.setText(String.valueOf(phong.getLoaiP()));
        txtTinhTrangP.setText(String.valueOf(phongDAL.demSoLuongMotPhong(phong.getMaP())));
        
        if(hd.isThanhToan() == true){
            txtTinhTrangHD.setText("ĐÃ THANH TOÁN");
            lblNgayTT.setVisible(true);
            txtNgayTT.setVisible(true);
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            txtNgayTT.setText(formatter.format(hd.getNgayTT()));
     
        }
        else {
            txtTinhTrangHD.setText("CHƯA THANH TOÁN");
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTenPhong = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNgayTT = new javax.swing.JLabel();
        monthChooser = new com.toedter.calendar.JMonthChooser();
        yearChooser = new com.toedter.calendar.JYearChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtLoaiPhong = new javax.swing.JTextField();
        txtNoiDungHD = new javax.swing.JTextField();
        txtTongHD = new javax.swing.JTextField();
        txtTinhTrangHD = new javax.swing.JTextField();
        txtNgayTT = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        txtTinhTrangP = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(94, 119, 141));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTenPhong.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTenPhong.setForeground(new java.awt.Color(255, 255, 255));
        lblTenPhong.setText("jLabel1");
        jPanel2.add(lblTenPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 44, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1260, 150));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Loại phòng");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 350, 120, 50));

        lblNgayTT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNgayTT.setText("Ngày thanh toán:");
        jPanel1.add(lblNgayTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 670, 170, 50));
        jPanel1.add(monthChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 100, 30));
        jPanel1.add(yearChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 90, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Hóa đơn tháng:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Tình trạng");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 430, 120, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Nội dung:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 170, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Tổng hóa đơn:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 170, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Tình trạng hóa đơn:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, 170, 50));
        jPanel1.add(txtLoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 360, 190, 30));
        jPanel1.add(txtNoiDungHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 190, 30));
        jPanel1.add(txtTongHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 190, 30));
        jPanel1.add(txtTinhTrangHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, 190, 30));
        jPanel1.add(txtNgayTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 680, 190, 30));

        jTextField6.setText("jTextField1");
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 360, 190, 30));
        jPanel1.add(txtTinhTrangP, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 440, 190, 30));

        jButton1.setBackground(new java.awt.Color(94, 119, 141));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.setBorder(null);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 120, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblNgayTT;
    private javax.swing.JLabel lblTenPhong;
    private com.toedter.calendar.JMonthChooser monthChooser;
    private javax.swing.JTextField txtLoaiPhong;
    private javax.swing.JTextField txtNgayTT;
    private javax.swing.JTextField txtNoiDungHD;
    private javax.swing.JTextField txtTinhTrangHD;
    private javax.swing.JTextField txtTinhTrangP;
    private javax.swing.JTextField txtTongHD;
    private com.toedter.calendar.JYearChooser yearChooser;
    // End of variables declaration//GEN-END:variables
}
