/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package qlktx;

import java.awt.Image;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import qlktx.BLL.HoaDonDienNuoc_BLL;
import qlktx.BLL.Phong_BLL;
import qlktx.BLL.Toa_BLL;
import qlktx.DTO.HoaDonDienNuoc_DTO;
import qlktx.DTO.Phong_DTO;
import qlktx.DTO.Toa_DTO;



/**
 *
 * @author ASUS
 */
public class qlhddnForm extends javax.swing.JPanel {

    HoaDonDienNuoc_BLL tthdBLL = new HoaDonDienNuoc_BLL();
    Toa_BLL toaBLL = new Toa_BLL();
    Phong_BLL phongBLL = new Phong_BLL();
    
    public qlhddnForm() {
        initComponents();
        this.setVisible(true);
        loadTableDSHD();
        loadCbbToa();
        loadCbbToa();
        txtMaHD.setEnabled(false);
        btnThanhToan.setEnabled(false);
    }
    ArrayList<HoaDonDienNuoc_DTO> listhd = new ArrayList<HoaDonDienNuoc_DTO>();
    DefaultTableModel tblModelDSHD;
    private void loadTableDSHD(){
        tblModelDSHD = new DefaultTableModel();
        
        String tieude[] = {"Mã HD", "Toa", "Phong", "Ngay Tao", "Ngay TT"};
        tblModelDSHD.setColumnIdentifiers(tieude);
        
        
        listhd = tthdBLL.timTatCaHoaDon();
        int arrsize = listhd.size();
        
        for(int i = 0;i < arrsize; i++){
            String mahd = listhd.get(i).getMaHD();
            String toa = listhd.get(i).getToa();
            String phong = listhd.get(i).getPhong();
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String ngtao = df.format(listhd.get(i).getNgayTao());
            String ngtt;
            if(listhd.get(i).isThanhToan() == true){
                ngtt = df.format(listhd.get(i).getNgayTT());
            }else{
                ngtt = "";
            }
            
            Object[] row = {mahd, toa, phong,ngtao, ngtt};
            tblModelDSHD.addRow(row);
        }
        
        tblDSHD.setModel(tblModelDSHD);
        setVisible(true);
    }

    ArrayList<Phong_DTO> listphg = new ArrayList<Phong_DTO>();
    ArrayList<Toa_DTO> listtoa= new ArrayList<Toa_DTO>();
    
    public void loadCbbToa(){
        listtoa.removeAll(listtoa);
        
        Toa_DTO toa = new Toa_DTO();
        
        listtoa = toaBLL.timTatCaToa();
        int size = listtoa.size();
        String name;
        ArrayList<String> listmatoa = new ArrayList<String>();
        
        for(int i = 0; i < size; i++){
            name = listtoa.get(i).getMaT();
            listmatoa.add(name);
        }
        //arrtoatrong.toString();
        cbbToa.setModel(new DefaultComboBoxModel<String>(
            listmatoa.toArray(new String[0])));
        loadCbbPhong();
    }
    private void loadCbbPhong(){
        listphg.removeAll(listphg);
        
        ArrayList<String> listmaphong = new ArrayList<String>();        
        
        String MaToa = listtoa.get(cbbToa.getSelectedIndex()).getMaT();
        System.out.println(MaToa);
        int size = toaBLL.demSoLuongPhong(MaToa);
        listphg = phongBLL.timPhongTheoToa(MaToa);
        
        for(int i = 0; i < size; i++){
            listmaphong.add(listphg.get(i).getMaP());
        }
        cbbPhong.setModel(new DefaultComboBoxModel<String>(
            listmaphong.toArray(new String[0])));
        //int slmp = phongBLL.demSoLuongMotPhong();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainer = new javax.swing.JPanel();
        pnlContainer1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        datNgTao = new com.toedter.calendar.JDateChooser();
        txtCTHD = new javax.swing.JTextField();
        txtTongTien = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSHD = new javax.swing.JTable();
        btnClear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbbToa = new javax.swing.JComboBox<>();
        cbbPhong = new javax.swing.JComboBox<>();
        btnTaoHD = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();

        setBackground(new java.awt.Color(94, 119, 141));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContainer1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Mã hóa đơn:");
        pnlContainer1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 120, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Phòng:");
        pnlContainer1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, 110, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Chi tiết hóa đơn:");
        pnlContainer1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, 180, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Ngày tạo:");
        pnlContainer1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, 130, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Tổng tiền:");
        pnlContainer1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, 130, -1));
        pnlContainer1.add(txtMaHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 120, 330, -1));
        pnlContainer1.add(datNgTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 380, 330, -1));

        txtCTHD.setText("Nhập chi tiết hóa đơn");
        pnlContainer1.add(txtCTHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 300, 330, 50));
        pnlContainer1.add(txtTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 440, 330, -1));

        tblDSHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDSHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblDSHDMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSHD);

        pnlContainer1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 590, -1));

        btnClear.setBackground(new java.awt.Color(68, 76, 88));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        pnlContainer1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 500, 120, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Tòa:");
        pnlContainer1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, 80, -1));

        cbbToa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbToa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbToaActionPerformed(evt);
            }
        });
        pnlContainer1.add(cbbToa, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, 330, -1));

        cbbPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlContainer1.add(cbbPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 240, 330, -1));

        btnTaoHD.setBackground(new java.awt.Color(68, 76, 88));
        btnTaoHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTaoHD.setForeground(new java.awt.Color(255, 255, 255));
        btnTaoHD.setText("Tạo hóa đơn");
        btnTaoHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoHDActionPerformed(evt);
            }
        });
        pnlContainer1.add(btnTaoHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 500, 120, 40));

        btnThanhToan.setBackground(new java.awt.Color(68, 76, 88));
        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhToan.setText("Thanh Toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });
        pnlContainer1.add(btnThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 500, 120, 40));

        pnlContainer.add(pnlContainer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 780));

        add(pnlContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 1340, 780));
    }// </editor-fold>//GEN-END:initComponents

    private void tblDSHDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSHDMousePressed
        int indexTB = tblDSHD.getSelectedRow();
        if(indexTB >= 0 && indexTB <= tblModelDSHD.getRowCount()){
            cbbToa.setEnabled(false);
            cbbPhong.setEnabled(false);
            datNgTao.setEnabled(false);
            txtTongTien.setEnabled(false);
            txtCTHD.setEnabled(false);
            btnTaoHD.setEnabled(false);
            btnThanhToan.setEnabled(true);
            
            String MaHD = tblModelDSHD.getValueAt(indexTB, 0).toString();
            txtMaHD.setText(MaHD);
            
            String Toa = tblModelDSHD.getValueAt(indexTB, 1).toString();
            cbbToa.setModel(new DefaultComboBoxModel <>(new String[]{Toa, Toa}));
            cbbToa.setEnabled(false);
            
            String Phong = tblModelDSHD.getValueAt(indexTB, 2).toString();
            cbbPhong.setModel(new DefaultComboBoxModel <>(new String[]{Phong, Phong}));
            cbbPhong.setEnabled(false);
            
            HoaDonDienNuoc_DTO hd = new HoaDonDienNuoc_DTO();
            hd = tthdBLL.timHoaDon(MaHD);
            String CTHD = hd.getChiTiet();
            txtCTHD.setText(CTHD);
            
            Date ngtao = hd.getNgayTao();
            datNgTao.setDate(ngtao);
            
            long tt = hd.getTongTien();
            txtTongTien.setText(String.valueOf(tt));
            
            if(hd.isThanhToan()){
                btnThanhToan.setEnabled(false);
            }
        }
        
        
    }//GEN-LAST:event_tblDSHDMousePressed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        loadTableDSHD();
        
        cbbToa.setEnabled(true);
        cbbPhong.setEnabled(true);
        datNgTao.setEnabled(true);
        txtTongTien.setEnabled(true);
        txtCTHD.setEnabled(true);
        btnTaoHD.setEnabled(true);
        btnThanhToan.setEnabled(false);
        cbbToa.setEnabled(true);
        cbbPhong.setEnabled(true);
        
        loadCbbToa();
        loadCbbPhong();
        txtMaHD.setText("");
        txtCTHD.setText("");
        txtTongTien.setText("");
        Date today = new Date();
        datNgTao.setDate(today);
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnTaoHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoHDActionPerformed
        //btnClear.setEnabled(false);// TODO add your handling code here:
        String mahd = tthdBLL.layMaHD();
        HoaDonDienNuoc_DTO hd = new HoaDonDienNuoc_DTO();
        hd.setMaHD(mahd);
        hd.setToa(listtoa.get(cbbToa.getSelectedIndex()).getMaT());
        hd.setPhong(listphg.get(cbbPhong.getSelectedIndex()).getMaP());
        hd.setChiTiet(txtCTHD.getText());
        hd.setNgayTao(datNgTao.getDate());
        hd.setThanhToan(false);
        Date today = new Date();
        hd.setNgayTT(today);
        hd.setTongTien(Integer.parseInt(txtTongTien.getText()));
        
        int check_flag = 1;//thêm Kiểm tra hóa đơn
        if(check_flag == 1){
            if(tthdBLL.themHoaDon(hd) == 1){
                loadTableDSHD();
                JOptionPane.showMessageDialog(null,"Thêm hóa đơn thành công",
                        "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null,"Thêm thất bại",
                        "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        } 
        
    }//GEN-LAST:event_btnTaoHDActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        HoaDonDienNuoc_DTO hd = tthdBLL.timHoaDon(txtMaHD.getText());
        
        hd.setThanhToan(true);
        int check_flag = 1;//thêm Kiểm tra hóa đơn
        if(check_flag == 1){
            if(tthdBLL.suaHoaDon(hd) == 1){
                loadTableDSHD();
                JOptionPane.showMessageDialog(null,"Thanh toán hóa đơn thành công",
                        "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null,"Thanh toán thất bại",
                        "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        } 
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void cbbToaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbToaActionPerformed
        loadCbbPhong();
    }//GEN-LAST:event_cbbToaActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnTaoHD;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JComboBox<String> cbbPhong;
    private javax.swing.JComboBox<String> cbbToa;
    private com.toedter.calendar.JDateChooser datNgTao;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlContainer1;
    private javax.swing.JTable tblDSHD;
    private javax.swing.JTextField txtCTHD;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
