/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package qlktx;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.temporal.Temporal;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import qlktx.DAL.Phong_DAL;
import qlktx.DAL.ThongBao_DAL;
import qlktx.DTO.Phong_DTO;
import qlktx.DTO.ThongBao_DTO;

/**
 *
 * @author ASUS
 */
public class qlpForm extends javax.swing.JPanel implements ActionListener {

    /**
     * Creates new form qlphongForm
     */
    int tang = 0;
    String MaTT;
    String maToa;
    ArrayList<JButton>  btnChiTiet = new ArrayList<JButton>();
    ArrayList<Phong_DTO> test = new ArrayList<Phong_DTO>();
    Phong_DAL pDAL = new Phong_DAL();
    Phong_DTO p = new Phong_DTO();


    public qlpForm(int tang, String maToa, String MaTT) {
        initComponents();
        this.tang = tang;
        this.maToa = maToa;
        this.MaTT=  MaTT;
        loadData();
    }
    
    public void loadData(){
    
        Phong_DAL pDAL = new Phong_DAL();
        test = pDAL.timPhongTheoToaVaTang(maToa, tang);
        if(test.size() == 0){
            System.out.println("????");
            JLabel lblNull = new JLabel();
            lblNull.setText("Chưa có thông báo");
            pnlQLPhong.add(lblNull);
        }else{
            System.out.println("hehehehehehe");
            int n = test.size(); 
            System.out.println("n= "+n);
           
            for(int i = 0; i < n; i++){
               JButton temp = new JButton();
              
               temp.setBackground(new Color(240,240,240));
               temp.setForeground(Color.BLACK);
               temp.setPreferredSize(new Dimension(200, 200));
               temp.setText("Phòng " + test.get(i).getMaP());
               temp.addActionListener(this);
               temp.setFocusable(false);
               pnlQLPhong.add(temp);
               btnChiTiet.add(temp);
              
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainer = new javax.swing.JPanel();
        pnlQLPhong = new javax.swing.JPanel();

        setBackground(new java.awt.Color(94, 119, 141));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlQLPhong.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 25, 25));
        pnlContainer.add(pnlQLPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 780));

        add(pnlContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 780));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlQLPhong;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        for(JButton x:btnChiTiet){
            if(e.getSource() == x){
                System.out.println("btnChiTiet: "+btnChiTiet.size());
                System.out.println("test: "+ test.size());
                int temp = btnChiTiet.indexOf(x);
                System.out.println("index of x: "+temp);
                p = test.get(temp);
                ctpForm ct = new ctpForm(p);
                ct.setVisible(true);
            }
        }
        
    }
}
