/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package qlktx;

import java.awt.Image;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import qlktx.BLL.SinhVien_BLL;
import qlktx.BLL.Toa_BLL;
import qlktx.DTO.SinhVien_DTO;
import qlktx.DTO.Toa_DTO;

/**
 *
 * @author ASUS
 */
public class qlsvForm extends javax.swing.JPanel {

    /**
     * Creates new form qlphongForm
     */
    SinhVien_BLL svBLL = new SinhVien_BLL();
    Toa_BLL toaBLL = new Toa_BLL();
    Toa_DTO toaDTO = new Toa_DTO();
    String MaTT;
     private JPanel childPanel;
    public qlsvForm(String id) {
        initComponents();        
        this.MaTT = id;
        LoadTableTTSV();
        
        toaDTO = toaBLL.timToaTheoTruongToa(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainer = new javax.swing.JPanel();
        pnlTableSV = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnTatCaSV = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTTSV = new javax.swing.JTable();
        btnLoupe = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();

        setBackground(new java.awt.Color(94, 119, 141));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContainer.setLayout(new javax.swing.BoxLayout(pnlContainer, javax.swing.BoxLayout.LINE_AXIS));

        pnlTableSV.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdate.setBackground(new java.awt.Color(237, 236, 164));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        pnlTableSV.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 460, 120, 40));

        btnDelete.setBackground(new java.awt.Color(236, 139, 139));
        btnDelete.setForeground(new java.awt.Color(255, 255, 102));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        pnlTableSV.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 460, 120, 40));

        btnTatCaSV.setText("Tất Cả SV");
        btnTatCaSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTatCaSVActionPerformed(evt);
            }
        });
        pnlTableSV.add(btnTatCaSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 460, 120, 40));

        tblTTSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTTSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblTTSVMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblTTSV);

        pnlTableSV.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 780));

        pnlContainer.add(pnlTableSV);

        add(pnlContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 1340, 780));

        btnLoupe.setBorder(null);
        btnLoupe.setFocusable(false);
        ImageIcon avt = new ImageIcon("image/loupe.png");
        Image userImage = avt.getImage();
        Image modifiedImage = userImage.getScaledInstance(30,30,java.awt.Image.SCALE_SMOOTH);
        avt = new ImageIcon(modifiedImage);
        btnLoupe.setIcon(avt);
        btnLoupe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLoupeMousePressed(evt);
            }
        });
        add(btnLoupe, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 40, 40));

        txtSearch.setText("Search");
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchMouseClicked(evt);
            }
        });
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 32, 1300, 40));
    }// </editor-fold>//GEN-END:initComponents
    
    DefaultTableModel tblModelTTSV;
    int tblCount;
    private void LoadTableTTSV(){
        tblModelTTSV = new DefaultTableModel();
        
        String tieude[] = {"MaSV", "CCCD", "Ten", "NgSinh", "DChi", "Truong",
            "Toa", "Phong", "SDT"};
        tblModelTTSV.setColumnIdentifiers(tieude);
        
        ArrayList<SinhVien_DTO> arrsv = new ArrayList<SinhVien_DTO>();
        
        arrsv = svBLL.timTatCaSinhVien();
        tblCount = arrsv.size();
              
        toaDTO = toaBLL.timToaTheoTruongToa(MaTT);
        
        for(int i = 0; i < tblCount; i++){
            SinhVien_DTO temp = new SinhVien_DTO();            
            temp = arrsv.get(i);
            
            String masv = temp.getMaSV();
            String cccd = temp.getCCCD();
            String ten = temp.getTen();
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String ngsinh = df.format(temp.getNgaySinh());
            String dchi = temp.getDiaChi();
            String truong = temp.getTruong();
            String toa = temp.getToa();
            String phong = temp.getPhong();
            String sdt = temp.getSoDT();
            
            String[] row = {masv, cccd, ten, ngsinh, dchi, truong, toa, phong, sdt};
            
            System.out.println(toaDTO.getMaT());
            if(flag_tcsv == true)
                tblModelTTSV.addRow(row);
            else{
                if(toaDTO.getMaT().equals(temp.getToa()) == true){
                    tblModelTTSV.addRow(row);
                }                
            }
        }
        tblTTSV.setModel(tblModelTTSV);
    }
    
    private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
        TimSV();
        txtSearch.setText("");
    }//GEN-LAST:event_txtSearchMouseClicked

    private void TimSV(){
        if(txtSearch.getText().equals("") == true){
            LoadTableTTSV();
        }else{
            tblModelTTSV.setRowCount(0);
            String name = txtSearch.getText();
            ArrayList<SinhVien_DTO> arrsv = svBLL.timTheoTen(name);

            for(int i = 0; i < arrsv.size(); i++){
                SinhVien_DTO temp = new SinhVien_DTO();

                temp = arrsv.get(i);
                String masv = temp.getMaSV();
                String cccd = temp.getCCCD();
                String ten = temp.getTen();
                DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                String ngsinh = df.format(temp.getNgaySinh());
                String dchi = temp.getDiaChi();
                String truong = temp.getTruong();
                String toa = temp.getToa();
                String phong = temp.getPhong();
                String sdt = temp.getSoDT();

                String[] row = {masv, cccd, ten, ngsinh, dchi, truong, toa, phong, sdt};
                tblModelTTSV.addRow(row);
            }
            tblTTSV.setModel(tblModelTTSV);
        }
    }
    
    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        TimSV();
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnLoupeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoupeMousePressed
        TimSV();
    }//GEN-LAST:event_btnLoupeMousePressed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int indexTB = tblTTSV.getSelectedRow();
        if(indexTB >= 0 && indexTB <= tblModelTTSV.getRowCount()){
            String MaSV = tblModelTTSV.getValueAt(indexTB, 0).toString();
            String Toa = tblModelTTSV.getValueAt(indexTB, 1).toString();
            childPanel = new nhapSV(MaSV, Toa);
            pnlTableSV.setVisible(false);
            pnlContainer.add(childPanel);
            pnlContainer.validate();
  
            // Gọi nhapSV... truyền MaSV và Toa (MaSV, Toa)
        }
    }//GEN-LAST:event_btnUpdateActionPerformed
    boolean flag_tcsv = false;
    private void btnTatCaSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTatCaSVActionPerformed
        flag_tcsv = true;
        LoadTableTTSV();
    }//GEN-LAST:event_btnTatCaSVActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int indexTB = tblTTSV.getSelectedRow();
        if(indexTB >= 0 && indexTB <= tblModelTTSV.getRowCount()){
            String MaSV = tblModelTTSV.getValueAt(indexTB, 0).toString();
            int choice = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn xóa dữ liệu?",
                        "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION){
                try{
                    int result = svBLL.xoaSinhVien(MaSV);
                    if(result != 0){
                        LoadTableTTSV();
                        JOptionPane.showMessageDialog(null, "Xóa dữ liệu thành công",
                                "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    }
                }catch(Exception ex){
                    ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblTTSVMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTTSVMousePressed
        
    }//GEN-LAST:event_tblTTSVMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLoupe;
    private javax.swing.JButton btnTatCaSV;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlTableSV;
    private javax.swing.JTable tblTTSV;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
