/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package qlktx;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author ASUS
 */
public class qltForm extends javax.swing.JPanel {

    /**
     * Creates new form qlphongForm
     */
    String maToa;
    String maTruongToa;
    private JPanel childPanel;
    int tang;
    public qltForm(String maToa, String maTruongToa) {
        initComponents();
        this.maToa = maToa;
        this.maTruongToa = maTruongToa;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainer = new javax.swing.JPanel();
        pnlQLTang = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnTang4 = new javax.swing.JButton();
        btnTang1 = new javax.swing.JButton();
        btnTang2 = new javax.swing.JButton();
        btnTang3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(94, 119, 141));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContainer.setLayout(new java.awt.BorderLayout());

        pnlQLTang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdate.setBackground(new java.awt.Color(237, 236, 164));
        btnUpdate.setText("Update");
        pnlQLTang.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 700, 120, 40));

        btnDelete.setBackground(new java.awt.Color(236, 139, 139));
        btnDelete.setForeground(new java.awt.Color(255, 255, 102));
        btnDelete.setText("Delete");
        pnlQLTang.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 700, 120, 40));

        btnTang4.setText("Tầng 4");
        btnTang4.setPreferredSize(new java.awt.Dimension(150, 150));
        btnTang4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTang4ActionPerformed(evt);
            }
        });
        pnlQLTang.add(btnTang4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        btnTang1.setText("Tầng 1");
        btnTang1.setPreferredSize(new java.awt.Dimension(150, 150));
        btnTang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTang1ActionPerformed(evt);
            }
        });
        pnlQLTang.add(btnTang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnTang2.setText("Tầng 2");
        btnTang2.setPreferredSize(new java.awt.Dimension(150, 150));
        btnTang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTang2ActionPerformed(evt);
            }
        });
        pnlQLTang.add(btnTang2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        btnTang3.setText("Tầng 3");
        btnTang3.setPreferredSize(new java.awt.Dimension(150, 150));
        btnTang3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTang3ActionPerformed(evt);
            }
        });
        pnlQLTang.add(btnTang3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        pnlContainer.add(pnlQLTang, java.awt.BorderLayout.CENTER);

        add(pnlContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 1340, 780));
    }// </editor-fold>//GEN-END:initComponents

    private void btnTang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTang1ActionPerformed
        // TODO add your handling code here:
        tang = 1;
        childPanel = new qlpForm(tang,maToa, maTruongToa);
        pnlQLTang.setVisible(false);
        pnlContainer.add(childPanel);
        pnlContainer.validate();
        
    }//GEN-LAST:event_btnTang1ActionPerformed

    private void btnTang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTang2ActionPerformed
        // TODO add your handling code here:
        tang = 2;
        childPanel = new qlpForm(tang,maToa, maTruongToa);
        pnlQLTang.setVisible(false);
        pnlContainer.add(childPanel);
        pnlContainer.validate();
    }//GEN-LAST:event_btnTang2ActionPerformed

    private void btnTang3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTang3ActionPerformed
        // TODO add your handling code here:
          tang = 3;
        childPanel = new qlpForm(tang,maToa, maTruongToa);
        pnlQLTang.setVisible(false);
        pnlContainer.add(childPanel);
        pnlContainer.validate();
    }//GEN-LAST:event_btnTang3ActionPerformed

    private void btnTang4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTang4ActionPerformed
        // TODO add your handling code here:
           tang = 4;
        childPanel = new qlpForm(tang,maToa, maTruongToa);
        pnlQLTang.setVisible(false);
        pnlContainer.add(childPanel);
        pnlContainer.validate();
    }//GEN-LAST:event_btnTang4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnTang1;
    private javax.swing.JButton btnTang2;
    private javax.swing.JButton btnTang3;
    private javax.swing.JButton btnTang4;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlQLTang;
    // End of variables declaration//GEN-END:variables
}
