/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlktx;
import java.awt.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.Box;
import javax.swing.JFrame;
import javax.swing.ImageIcon;
import qlktx.BLL.Phong_BLL;
import qlktx.BLL.SinhVien_BLL;
import qlktx.BLL.TruongToa_BLL;
import qlktx.DAL.SinhVien_DAL;
import qlktx.DTO.Phong_DTO;
import qlktx.DTO.SinhVien_DTO;
import qlktx.DTO.TruongToa_DTO;
/**
 *
 * @author Administrator
 */
public class SVFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    CardLayout cardlayout;
    String MaSV;
    
    public SVFrame(String id) {
        //setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
        cardlayout = (CardLayout)(pnlCards.getLayout());
        pnlMenu.setSize(200,400);
        pnlMenu.add(Box.createRigidArea(new Dimension(0,10)));
        MaSV = id;
        this.setVisible(true);
        loadTTCN();
    }
    public SVFrame() {
        initComponents();
        cardlayout = (CardLayout)(pnlCards.getLayout());
        pnlMenu.setSize(200,400);
        pnlMenu.add(Box.createRigidArea(new Dimension(0,10)));
        this.setVisible(true);
        loadTTCN();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        btnTTLT = new javax.swing.JButton();
        btnTTCN = new javax.swing.JButton();
        btnThongBao = new javax.swing.JButton();
        pnlCards = new javax.swing.JPanel();
        pnlTTCN = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTruong = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        pnlTTLT = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtToa = new javax.swing.JTextField();
        txtPhong = new javax.swing.JTextField();
        txtLoaiPhong = new javax.swing.JTextField();
        pnlThongBao = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setLayout(new java.awt.BorderLayout());

        pnlMenu.setBackground(new java.awt.Color(68, 76, 88));
        pnlMenu.setFocusable(false);
        pnlMenu.setPreferredSize(new java.awt.Dimension(200, 554));
        pnlMenu.setLayout(new java.awt.GridBagLayout());

        btnTTLT.setBackground(new java.awt.Color(68, 76, 88));
        btnTTLT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTTLT.setForeground(new java.awt.Color(255, 255, 255));
        btnTTLT.setText("Thông Tin Lưu Trú");
        btnTTLT.setAlignmentX(CENTER_ALIGNMENT
        );
        btnTTLT.setBorder(null);
        btnTTLT.setFocusable(false);
        btnTTLT.setMargin(new java.awt.Insets(100, 50, 100, 50));
        btnTTLT.setMaximumSize(new java.awt.Dimension(101, 50));
        btnTTLT.setMinimumSize(new java.awt.Dimension(101, 50));
        btnTTLT.setPreferredSize(new java.awt.Dimension(224, 40));
        btnTTLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTTLTActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 111;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 25, 0);
        pnlMenu.add(btnTTLT, gridBagConstraints);

        btnTTCN.setBackground(new java.awt.Color(57, 63, 72));
        btnTTCN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTTCN.setForeground(new java.awt.Color(255, 255, 255));
        btnTTCN.setText("Thông Tin Cá Nhân");
        btnTTCN.setAlignmentX(CENTER_ALIGNMENT);
        btnTTCN.setBorder(null);
        btnTTCN.setFocusable(false);
        btnTTCN.setMargin(new java.awt.Insets(200, 50, 200, 50));
        btnTTCN.setMaximumSize(new java.awt.Dimension(224, 50));
        btnTTCN.setMinimumSize(new java.awt.Dimension(224, 50));
        btnTTCN.setPreferredSize(new java.awt.Dimension(224, 40));
        btnTTCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTTCNActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 25, 0);
        pnlMenu.add(btnTTCN, gridBagConstraints);

        btnThongBao.setBackground(new java.awt.Color(68, 76, 88));
        btnThongBao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThongBao.setForeground(new java.awt.Color(255, 255, 255));
        btnThongBao.setText("Thông Báo");
        btnThongBao.setAlignmentX(CENTER_ALIGNMENT);
        btnThongBao.setBorder(null);
        btnThongBao.setFocusable(false);
        btnThongBao.setMargin(new java.awt.Insets(200, 50, 200, 50));
        btnThongBao.setMaximumSize(new java.awt.Dimension(224, 50));
        btnThongBao.setMinimumSize(new java.awt.Dimension(224, 50));
        btnThongBao.setPreferredSize(new java.awt.Dimension(224, 40));
        btnThongBao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongBaoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 25, 0);
        pnlMenu.add(btnThongBao, gridBagConstraints);

        jPanel1.add(pnlMenu, java.awt.BorderLayout.LINE_START);

        pnlCards.setBackground(new java.awt.Color(0, 153, 153));
        pnlCards.setLayout(new java.awt.CardLayout());

        pnlTTCN.setBackground(new java.awt.Color(255, 255, 255));
        pnlTTCN.setLayout(new javax.swing.BoxLayout(pnlTTCN, javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setBackground(new java.awt.Color(94, 119, 141));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Họ và tên:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 140, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ngày sinh:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 130, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Trường:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quê quán:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Số điện thoại:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        txtTruong.setEditable(false);
        txtTruong.setBackground(new java.awt.Color(94, 119, 141));
        txtTruong.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTruong.setForeground(new java.awt.Color(255, 255, 255));
        txtTruong.setBorder(null);
        jPanel3.add(txtTruong, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 450, 40));

        txtTen.setEditable(false);
        txtTen.setBackground(new java.awt.Color(94, 119, 141));
        txtTen.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTen.setForeground(new java.awt.Color(255, 255, 255));
        txtTen.setBorder(null);
        jPanel3.add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 450, 30));

        txtNgaySinh.setEditable(false);
        txtNgaySinh.setBackground(new java.awt.Color(94, 119, 141));
        txtNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtNgaySinh.setForeground(new java.awt.Color(255, 255, 255));
        txtNgaySinh.setBorder(null);
        jPanel3.add(txtNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 450, 30));

        txtDiaChi.setEditable(false);
        txtDiaChi.setBackground(new java.awt.Color(94, 119, 141));
        txtDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtDiaChi.setForeground(new java.awt.Color(255, 255, 255));
        txtDiaChi.setBorder(null);
        jPanel3.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 450, 30));

        txtSoDienThoai.setEditable(false);
        txtSoDienThoai.setBackground(new java.awt.Color(94, 119, 141));
        txtSoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtSoDienThoai.setForeground(new java.awt.Color(255, 255, 255));
        txtSoDienThoai.setBorder(null);
        jPanel3.add(txtSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 450, 30));

        pnlTTCN.add(jPanel3);

        pnlCards.add(pnlTTCN, "pnlTTCN");

        pnlTTLT.setBackground(new java.awt.Color(94, 119, 141));
        pnlTTLT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tòa:");
        pnlTTLT.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 140, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phòng:");
        pnlTTLT.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 130, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Loại phòng:");
        pnlTTLT.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        txtToa.setEditable(false);
        txtToa.setBackground(new java.awt.Color(94, 119, 141));
        txtToa.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtToa.setForeground(new java.awt.Color(255, 255, 255));
        txtToa.setBorder(null);
        pnlTTLT.add(txtToa, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 450, 30));

        txtPhong.setEditable(false);
        txtPhong.setBackground(new java.awt.Color(94, 119, 141));
        txtPhong.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtPhong.setForeground(new java.awt.Color(255, 255, 255));
        txtPhong.setBorder(null);
        pnlTTLT.add(txtPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 450, 30));

        txtLoaiPhong.setEditable(false);
        txtLoaiPhong.setBackground(new java.awt.Color(94, 119, 141));
        txtLoaiPhong.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtLoaiPhong.setForeground(new java.awt.Color(255, 255, 255));
        txtLoaiPhong.setBorder(null);
        pnlTTLT.add(txtLoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 450, 30));

        pnlCards.add(pnlTTLT, "pnlTTLT");

        pnlThongBao.setBackground(new java.awt.Color(255, 102, 102));
        pnlThongBao.setMinimumSize(new java.awt.Dimension(1240, 1024));
        pnlThongBao.setLayout(new java.awt.BorderLayout());
        pnlCards.add(pnlThongBao, "pnlThongBao");

        jPanel1.add(pnlCards, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadTTLT(){
        SinhVien_DTO sv = new SinhVien_DTO();
        SinhVien_BLL svBLL = new SinhVien_BLL();
        Phong_DTO phong = new Phong_DTO();
        Phong_BLL phongBLL = new Phong_BLL();
        
        sv = svBLL.timSinhVien(MaSV);
        phong = phongBLL.timPhong(sv.getPhong(),sv.getToa());
        
        txtLoaiPhong.setText(String.valueOf(phong.getLoaiP()));
        txtPhong.setText(sv.getPhong());
        txtToa.setText(sv.getToa());
    }
    private void btnTTLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTTLTActionPerformed
        // TODO add your handling code here:
        cardlayout.show(pnlCards,"pnlTTLT");
        btnTTLT.setBackground(new Color(57,63,72));
        btnTTCN.setBackground(new Color(68,75,88));
        btnThongBao.setBackground(new Color(68,75,88));
        loadTTLT();
     
    }//GEN-LAST:event_btnTTLTActionPerformed
    public void loadTTCN(){
        SinhVien_DTO sv = new SinhVien_DTO();
        SinhVien_BLL svBLL = new SinhVien_BLL();

        sv = svBLL.timSinhVien(MaSV);
        txtTen.setText(sv.getTen());
        txtDiaChi.setText(sv.getDiaChi());
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        txtNgaySinh.setText(df.format(sv.getNgaySinh()));
        txtDiaChi.setText(sv.getDiaChi());
        txtSoDienThoai.setText(sv.getSoDT());
        txtTruong.setText(sv.getTruong());
    }
    
    public void loadTB(){
        SinhVien_DTO sv = new SinhVien_DTO();
        SinhVien_BLL svBLL = new SinhVien_BLL();
        sv = svBLL.timSinhVien(MaSV);
        TruongToa_DTO tt = new TruongToa_DTO();
        TruongToa_BLL ttBLL = new TruongToa_BLL();
        tt = ttBLL.timTruongToaTheoToa(sv.getToa());
    }
    private void btnTTCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTTCNActionPerformed
        // TODO add your handling code here:
        cardlayout.show(pnlCards,"pnlTTCN");
        btnTTCN.setBackground(new Color(57,63,72));
        btnTTLT.setBackground(new Color(68,75,88));
        btnThongBao.setBackground(new Color(68,75,88));
        loadTTCN();
        
    }//GEN-LAST:event_btnTTCNActionPerformed

    private void btnThongBaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongBaoActionPerformed
        // TODO add your handling code here:
        cardlayout.show(pnlCards,"pnlThongBao");
        btnTTCN.setBackground(new Color(68,75,88));
        btnTTLT.setBackground(new Color(68,75,88));
        btnThongBao.setBackground(new Color(57,63,72));
        SinhVien_DTO sv = new SinhVien_DTO();
        SinhVien_BLL svBLL = new SinhVien_BLL();
        sv = svBLL.timSinhVien(MaSV);
        TruongToa_DTO tt = new TruongToa_DTO();
        TruongToa_BLL ttBLL = new TruongToa_BLL();
        tt = ttBLL.timTruongToaTheoToa(sv.getToa());
        pnlThongBao.add(new SVqltbForm(tt.getMaTT(), MaSV));
    }//GEN-LAST:event_btnThongBaoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SVFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SVFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SVFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SVFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SVFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTTCN;
    private javax.swing.JButton btnTTLT;
    private javax.swing.JButton btnThongBao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel pnlCards;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlTTCN;
    private javax.swing.JPanel pnlTTLT;
    private javax.swing.JPanel pnlThongBao;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtLoaiPhong;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtPhong;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtToa;
    private javax.swing.JTextField txtTruong;
    // End of variables declaration//GEN-END:variables
}
