/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package qlktx;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import qlktx.BLL.ThongBao_BLL;
import qlktx.DAL.ThongBao_DAL;
import qlktx.DTO.ThongBao_DTO;

/**
 *
 * @author ASUS
 */
public class SVqltbForm extends javax.swing.JPanel implements ActionListener  {

    /**
     * Creates new form qlphongForm
     */
    
    private String tacgia;
    private String sinhvien;

            
    ArrayList<ThongBao_DTO> test = new ArrayList<ThongBao_DTO>();
    ThongBao_DAL tbDAL = new ThongBao_DAL();
    ArrayList<JButton>  btnChiTiet = new ArrayList<JButton>();
    ThongBao_DTO tb = new ThongBao_DTO();
      
    public SVqltbForm(String id, String sinhvien) {
        initComponents();
       
        this.tacgia = id;
        this.sinhvien = sinhvien;
        
        loadData();
        System.out.println(this.tacgia);      
    }
  
    public void loadData(){
        test = tbDAL.timTatCaThongBaoTheoTruongToa(tacgia);
        if(test.size() == 0){ 
            JLabel lblNull = new JLabel();
            lblNull.setText("Chưa có thông báo");
            pnlThongBao.add(lblNull);
        }else{
            int n = test.size();
            System.out.println(n);
            pnlThongBao.setPreferredSize(new Dimension(1160,150 * n + 200));
            for(int i = 0; i < n; i++){
               JButton temp = new JButton();
               temp.setBackground(new Color(230,230,230));
               temp.setPreferredSize(new Dimension(1040, 150));
               temp.setText(test.get(i).getChuDe());
               temp.addActionListener(this);
               pnlThongBao.add(temp);
               btnChiTiet.add(temp);
               
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlThongBao = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(94, 119, 141));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(50, 50));

        pnlThongBao.setBackground(new java.awt.Color(255, 255, 255));
        pnlThongBao.setMaximumSize(new java.awt.Dimension(20, 20));
        pnlThongBao.setPreferredSize(new java.awt.Dimension(1160, 1000000));
        pnlThongBao.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 25));
        jScrollPane1.setViewportView(pnlThongBao);

        pnlContainer.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 780));

        add(pnlContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 1160, 780));

        btnRefresh.setBackground(new java.awt.Color(94, 119, 141));
        btnRefresh.setActionCommand("btnBack");
        btnRefresh.setBorder(null);
        btnRefresh.setFocusable(false);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 70, 70));
        ImageIcon icon = new ImageIcon("image/refresh.png");
        Image refreshIcon = icon.getImage();
        Image modifiedIcon = refreshIcon.getScaledInstance(30,30,java.awt.Image.SCALE_SMOOTH);
        icon = new ImageIcon(modifiedIcon);
        btnRefresh.setIcon(icon);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        pnlThongBao.removeAll();
        pnlThongBao.revalidate();
        pnlThongBao.repaint();
        pnlThongBao.removeAll();
        btnChiTiet.clear();
        loadData();
        //btnChiTiet.clear();
    
       
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlThongBao;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
       
        for(JButton x:btnChiTiet){
            if(e.getSource() == x){
                int temp = btnChiTiet.indexOf(x);
                this.tb = test.get(temp);
                ThongBaoForm tb = new ThongBaoForm(tacgia, test.get(temp).getMaTB(), sinhvien);
                tb.setVisible(true);
            }
        }
        
    }

 
}
