/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlktx;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import qlktx.BLL.Toa_BLL;
import qlktx.DAL.Toa_DAL;
import qlktx.DTO.Toa_DTO;

/**
 *
 * @author ASUS
 */
public class TTFrame extends javax.swing.JFrame {
    private JPanel childPanel;
    /**
     * Creates new form TTFrame
     */
    
    private String matoa;
    private String id;
    public TTFrame(String ID) {
        initComponents();
        this.setTitle("Quản Lý Kí Túc Xá");
        id = ID;
        Toa_BLL tBLL = new Toa_BLL();
        Toa_DTO t = new Toa_DTO();
        Toa_DAL tDAL = new Toa_DAL();
        
        t = tDAL.timToaTheoTruongToa(id);
        matoa = t.getMaT();
        btnBack.setVisible(false);
    }
   
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        pnlQuanLy = new javax.swing.JPanel();
        btnQLSV = new javax.swing.JButton();
        btnQLP = new javax.swing.JButton();
        btnTB = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pnlMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(68, 76, 88));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(68, 76, 88));
        btnBack.setActionCommand("btnBack");
        ImageIcon avt = new ImageIcon("image/left-arrow.png");
        Image userImage = avt.getImage();
        Image modifiedImage = userImage.getScaledInstance(30,30,java.awt.Image.SCALE_SMOOTH);
        avt = new ImageIcon(modifiedImage);
        btnBack.setIcon(avt);
        btnBack.setVisible(false);
        btnBack.setBorder(null);
        btnBack.setFocusable(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 50, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 80));

        pnlQuanLy.setBackground(new java.awt.Color(94, 119, 141));
        pnlQuanLy.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnQLSV.setText("Quản lý sinh viên");
        btnQLSV.setAlignmentY(0.0F);
        btnQLSV.setPreferredSize(new java.awt.Dimension(940, 420));
        btnQLSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLSVActionPerformed(evt);
            }
        });
        pnlQuanLy.add(btnQLSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 950, -1));

        btnQLP.setText("Quản Lý Phòng");
        btnQLP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLPActionPerformed(evt);
            }
        });
        pnlQuanLy.add(btnQLP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 480, 480));

        btnTB.setText("Quản Lý Thông Báo");
        btnTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTBActionPerformed(evt);
            }
        });
        pnlQuanLy.add(btnTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 460, 480));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlQuanLy.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, 450, 910));

        getContentPane().add(pnlQuanLy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1440, 950));

        pnlMain.setBackground(new java.awt.Color(94, 119, 141));
        pnlMain.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1440, 950));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSVActionPerformed
        // TODO add your handling code here:
        childPanel = new qlsvForm(id);
       // childPanel = new nhapSV("sv0001", "g01");
       // childPanel = new qlhddn();
        btnBack.setVisible(true);
        pnlQuanLy.setVisible(false);
        pnlMain.add(childPanel);
        pnlMain.validate();
    }//GEN-LAST:event_btnQLSVActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        pnlMain.removeAll();
        pnlQuanLy.setVisible(true);
     
        
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTBActionPerformed
        // TODO add your handling code here:
        childPanel = new qltbForm(id);
        btnBack.setVisible(true);
        pnlQuanLy.setVisible(false);
        pnlMain.add(childPanel);
        pnlMain.validate();
    }//GEN-LAST:event_btnTBActionPerformed

    private void btnQLPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLPActionPerformed
        // TODO add your handling code here:
        childPanel = new qltForm(matoa,id);
        btnBack.setVisible(true);
        pnlQuanLy.setVisible(false);
        pnlMain.add(childPanel);
        pnlMain.validate();
    }//GEN-LAST:event_btnQLPActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnQLP;
    private javax.swing.JButton btnQLSV;
    private javax.swing.JButton btnTB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlQuanLy;
    // End of variables declaration//GEN-END:variables
}
